//
//  NewsFeedRouter.swift
//  VKCleanSwift
//
//  Created by Sergey Koriukin on 03/09/2019.
//  Copyright (c) 2019 Sergey Koriukin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol NewsFeedRoutingLogic {
    
}

class NewsFeedRouter: NSObject, NewsFeedRoutingLogic {
    
    weak var viewController: NewsFeedViewController?
    
    // MARK: Routing
    
}
