//
//  NewsFeedModels.swift
//  VKCleanSwift
//
//  Created by Sergey Koriukin on 03/09/2019.
//  Copyright (c) 2019 Sergey Koriukin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsFeed {
    
    enum Model {
        struct Request {
            enum RequestType {
                case some
            }
        }
        struct Response {
            enum ResponseType {
                case some
            }
        }
        struct ViewModel {
            enum ViewModelData {
                case some
            }
        }
    }
   
}
